# Generated by Django 3.0.6 on 2020-06-02 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=16)),
                ('gen_date', models.DateTimeField(verbose_name='date account created')),
                ('creator_handle', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype', models.CharField(max_length=10)),
                ('video_name', models.CharField(max_length=20)),
                ('video_date', models.DateTimeField(verbose_name='date published')),
                ('misc_data', models.CharField(max_length=20)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype', models.CharField(max_length=10)),
                ('essay_title', models.CharField(max_length=30)),
                ('essay_date', models.DateTimeField(verbose_name='date published')),
                ('misc_data', models.CharField(max_length=20)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype', models.CharField(max_length=10)),
                ('drawing_name', models.CharField(max_length=20)),
                ('drawing_date', models.DateTimeField(verbose_name='date published')),
                ('misc_data', models.CharField(max_length=20)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Project')),
            ],
        ),
    ]
